apiVersion: v1
kind: Secret
metadata:
  name: hetzner-dns-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-key: {{ .Values.hetzner.apiToken }}
  
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.hetzner.com
            solverName: hetzner
            config:
              tokenSecretKeyRef:
                name: hetzner-dns-credentials
                key: api-key
