# {{- if .Values.oneTimeBackup }}

apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: {{ .Release.Name }}
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: "{{ .Release.Name }}-repopassword"
      key: password
    s3:
      endpoint: "{{ .Values.endpoint }}"
      bucket: "{{ .Values.bucket }}"
      accessKeyIDSecretRef:
         name: "{{ .Release.Name }}-credentials"
         key: id
      secretAccessKeySecretRef:
         name: "{{ .Release.Name }}-credentials"
         key: key    
# {{- end }}
