# {{- if not .Values.oneTimeBackup }}
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: "{{ .Release.Name }}-schedule"
spec:
  backend:
    repoPasswordSecretRef:
      name: "{{ .Release.Name }}-repopassword"
      key: password
    s3:
      endpoint: "{{ .Values.endpoint }}"
      bucket: "{{ .Values.bucket }}"
      accessKeyIDSecretRef:
         name: "{{ .Release.Name }}-credentials"
         key: id
      secretAccessKeySecretRef:
         name: "{{ .Release.Name }}-credentials"
         key: key    
  backup:
    schedule: '@hourly-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
  check:
    schedule: '@daily-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
  prune:
    schedule: '@weekly-random'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 1
    retention:
      keepLast: 5
      keep Daily: 14
# {{- end }}
