apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-credentials"
data:
  id: "{{ .Values.credentials.id | b64enc}}"
  key: "{{ .Values.credentials.key | b64enc}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-repopassword"
data:
  password: "{{ .Values.repoPassword | b64enc}}"
