kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-matrix-registration" .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  100M
