apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ printf "%s-matrix-registration" .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`goatchat.ca`) && PathPrefix(`/gate/`)
    kind: Rule
    services:
    - kind: Service
      name: {{ printf "%s-matrix-registration" .Release.Name }}
      port: 5000
  tls:
    certResolver: letsencrypt
