apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-matrix-registration" .Release.Name }}
spec:
  selector:
    app: matrix-registration
  ports:
    - name: web
      protocol: TCP
      port: 5000
