image:
  debug: true

ghostBlogTitle: K&G Tie the Kgnot
ghostHost: https://kgnot.ca
ghostUsername: # set through cli args
existingSecret: ghost-kgnot-user-secret

allowEmptyPassword: false


readinessProbe:
  enabled: false
  
persistence:
  size: 1Gi

smtpHost: "smtp.sendgrid.net"
smtpPort: 465
smtpUser: "apikey"
smtpService: "SendGrid"
smtpProtocol: "tls"
smtpExistingSecret: kgnot-smtp-password

mysql:
  enabled: false
externalDatabase:
  host: mariadb.datastore.svc.cluster.local
  user: kgnot_ghost
  database: kgnot_ghost
  existingSecret: ghost-kgnot-db-secret
   
updateStrategy:
  type: Recreate

service:
  type: ClusterIP
  
ingress:
  enabled: true
  hostname: kgnot.ca
  tls: true
  annotations:
    "traefik.ingress.kubernetes.io/router.tls.certresolver": "letsencrypt"
