alloy:
  configMap:
    content: |-
      logging {
      	level  = "info"
      	format = "logfmt"
      }
      
      discovery.kubernetes "pods" {
        role = "pod"
      }
      
      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.loki.receiver]

      }
      
      loki.write "loki" {
         endpoint {
           url = "http://loki.grafana.svc.cluster.local:3100/loki/api/v1/push"
         }
       }
