grafana:
  ingress:
    enabled: true
    hosts:
      - watcher.incngrnt.ca
    annotations:
      "traefik.ingress.kubernetes.io/router.tls.certresolver": "letsencrypt"

  persistence:
    enabled: true    

mimir:
  mimir:
    structuredConfig:
      limits:
        compactor_blocks_retention_period: 2h
  ingester:
    persistentVolume:
      size: 5Gi
