init:
  method: wget
  wget:
    url: https://git.incngrnt.ca/grant/incngrnt/releases/download/v0.0.8/v0.0.8.tar

ingress:
  enabled: true
  annotations:
    "traefik.ingress.kubernetes.io/router.tls.certresolver": "letsencrypt"  
  hosts:
    - host: incngrnt.ca
      paths:
        - path: /
          pathType: ImplementationSpecific
