persistent:
  size: 5Gi

primary:
  resources:
        limits:
          cpu: 375m
          ephemeral-storage: 2Gi
          memory: 384Mi
        requests:
          cpu: 50m
          ephemeral-storage: 50Mi
          memory: 256Mi
  
