repositories:
  - name: rook-release
    url:  https://charts.rook.io/release
  - name: traefik
    url: https://traefik.github.io/charts
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: cert-manager-webhook-hetzner
    url: https://vadimkim.github.io/cert-manager-webhook-hetzner

lockFilePath: ./helmfile.d/01-infrastructure.lock
releases:
  # networking
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: ../metallb
    values:
      - ../metallb/values.yaml.gotmpl
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    values:
      - ../cert-manager/values.yaml.gotmpl
  - name: cert-manager-webhook-hetzner
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager-webhook-hetzner/cert-manager-webhook-hetzner
    values:
      - ../cert-manager-hetzner-webhook/values.yaml.gotmpl
  - name: cert-manager-issuers
    namespace: cert-manager
    createNamespace: true
    chart: ../cert-manager-issuers
    values:
      - ../cert-manager-issuers/values.yaml.gotmpl    
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    values:
      - ../traefik/values.yaml.gotmpl
  - name: tailscale-operator
    namespace: tailscale
    createNamespace: true
    chart: tailscale/tailscale-operator
    values:
      - ../tailscale/values.yaml.gotmpl

  # storage infrastructure
  - name: rook-ceph
    namespace: rook-ceph
    createNamespace: true
    chart: rook-release/rook-ceph
    values:
      - ../rook-ceph/values.yaml.gotmpl
  - name: rook-ceph-cluster
    namespace: rook-ceph
    createNamespace: true
    chart: rook-release/rook-ceph-cluster
    values:
      - ../rook-ceph-cluster/values.yaml.gotmpl
    set:
      - name: operatorNamespace
        value: rook-ceph 
