repositories:
  - name: crunchydata
    url: git+https://github.com/grantdhunter/postgres-operator@helm?ref=main
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: k8up-io
    url: https://k8up-io.github.io/k8up

lockFilePath: ./helmfile.d/02-datastore.lock
releases:
  # data storage
  - name: pgo
    namespace: postgres-operator
    createNamespace: true
    chart: crunchydata/pgo
    values:
      - ../postgres/operator-values.yaml.gotmpl
  - name: postgres
    namespace: datastore
    createNamespace: true
    chart: crunchydata/postgrescluster
    values:
      - ../postgres/values.yaml.gotmpl
  - name: mariadb
    namespace: datastore
    createNamespace: true
    chart: bitnami/mariadb
    values:
      - ../mariadb/values.yaml.gotmpl

  # backup infrastructure
  - name: k8up
    namespace: k8up
    createNamespace: true
    chart: k8up-io/k8up
    values:
      - ../k8up/values.yaml.gotmpl 
