repositories:
  - name: ananace-charts
    url: https://ananace.gitlab.io/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: immich
    url: https://immich-app.github.io/immich-charts
  - name: gitea
    url: https://dl.gitea.io/charts
  - name: static-site
    url: git+https://github.com/cfpb/static-site@charts?ref=main
  - name: incngrnt
    url: git+https://git.incngrnt.ca/grant/charts@charts?ref=main

releases:
  # goatchat matrix
  - name: goatchat
    namespace: goatchat
    createNamespace: true
    chart: ananace-charts/matrix-synapse
    values:
      - ../synapse/values.yaml.gotmpl
  - name: gate
    namespace: goatchat
    createNamespace: true
    chart: incngrnt/matrix-registration
    values:
      - ../matrix-registration/values.yaml.gotmpl

  - name: immich
    namespace: immich
    createNamespace: true
    chart: immich/immich
    values:
      - ../immich/values.yaml.gotmpl
      
  # website
  - name: incngrnt-web
    namespace: incngrnt-web
    createNamespace: true
    chart: static-site/static-site
    values:
      - ../incngrnt-web/values.yaml
  # ghost blogs
  - name: kgnot-ghost
    namespace: ghost
    createNamespace: true
    chart: bitnami/ghost
    values:
      - ../kgnot/values.yaml.gotmpl
  - name: ghost-53ll
    namespace: ghost
    createNamespace: true
    chart: bitnami/ghost
    values:
      - ../53ll/values.yaml.gotmpl

  # dev tools
  # - name: gitea
  #   namespace: gitea
  #   createNamespace: true
  #   chart: gitea/gitea
  #   values:
  #     - ../gitea/values.yaml.gotmpl

  # backups
  - name: ghost-backup
    namespace: ghost
    chart: incngrnt/k8up-backup
    createNamespace: true    
    values:
      - ../k8up-backup/values.yaml.gotmpl
  - name: goatchat-backup
    namespace: goatchat
    chart: incngrnt/k8up-backup
    createNamespace: true    
    values:
      - ../k8up-backup/values.yaml.gotmpl
  - name: gitea-backup
    namespace: gitea
    chart: incngrnt/k8up-backup
    createNamespace: true    
    values:
      - ../k8up-backup/values.yaml.gotmpl
  - name: immich-backup
    namespace: immich
    chart: incngrnt/k8up-backup
    createNamespace: true    
    values:
      - ../k8up-backup/values.yaml.gotmpl  
