repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # monitoring
  - name: grafana
    namespace: grafana
    createNamespace: true
    chart: grafana/lgtm-distributed
    values:
      - ../grafana/values.yaml
  - name: alloy
    namespace: grafana
    createNamespace: true
    chart: grafana/alloy
    values:
      - ../grafana/alloy_values.yaml
  - name: kube-state-metrics
    namespace: grafana
    createNamespace: true
    chart: prometheus-community/kube-state-metrics 