instanceSize: 10Gi
backupsSize: 10Gi

patroni:
  dynamicConfiguration:
    postgresql:
      pg_hba:
        - "host all all all scram-sha-256"

users:
  - name: grant
    databases:
      - postgres
      - synapse
      - gitea     
    options: "SUPERUSER LOGIN"
  - name: synapse
    databases:
      - synapse
    options: "LOGIN"
  - name: gitea
    databases:
      - gitea
    options: "LOGIN"      
    
    
  
